# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Book & Go' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Book & Go

  pod 'Firebase/Core'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'Book & GoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Book & GoUITests' do
    # Pods for testing
  end

end
